config/routes.rb
Rails.application.routes.draw do

    # 404/500 pages
    get 'errors/not_found'
    get 'errors/internal_server_error'
    match "/404", to: "errors#not_found", via: :all
    match "/500", to: "errors#internal_server_error", via: :all
  
  #devise_scope :admins do
  #  # Redirests signing out users back to sign-in
  #  get "admins", to: "devise/sessions#new"
  #end

  devise_for :admins, controllers: { registrations: "registrations", sessions: "sessions" }
  root "pages#home"   #---- UNCOMMENT For HOME PAGE.
  #root "pages#template_start"  # --- Hello World Home page

  #post 'uploader/image', to: 'uploader#image' #add upload image to posts 
  get 'blog', to: 'posts#index', as: :blog
  #resources :posts
  
  #resources :discover_flights
  #resources :messages
  #resources :enrollments
  #resources :book_downloads
  #resources :checkouts
  #resources :quiz_results

  # Enrollment form
  get 'enroll-at-simplifly', to: 'enrollments#new', as: :enroll
  get 'enrollment-confirmation', to: 'enrollments#confirmation', as: :enroll_confirmation

  # Contact form
  get 'contact', to: 'messages#new', as: :contact
  get 'contact-confirmation', to: 'messages#confirmation', as: :contact_confirmation
  get 'visit-simplifly', to: 'messages#location', as: :location
  get 'instruct-at-simplifly', to: 'messages#cfi', as: :cfi

  # Book Download
  get 'book-download-confirmation', to: 'book_downloads#confirmation', as: :book_download_confirmation

  # Discovery flight form
  get 'discovery-flight', to: 'discover_flights#new', as: :discovery_flight
  get 'discovery-flight-confirmation', to: 'discover_flights#confirmation', as: :discovery_confirmation

  # Check out form
  #get 'rental-checkout', to: 'checkouts#new', as: :rental_checkout
  #get 'rental-checkout-confirmation', to: 'checkouts#confirmation', as: :checkout_confirmation

  # Quiz form
  #get 'quiz', to: 'quiz_results#new', as: :quiz
  #get 'quiz-confirmation', to: 'quiz_results#confirmation', as: :quiz_confirmation

  # Static Pages
  get 'stratus-finance', to: 'pages#stratus', as: :stratus
  get 'meritize', to: 'pages#meritize', as: :meritize
  get 'accelerated-pilot-training', to: 'pages#accelerated', as: :accelerated
  get 'flexible-pilot-training', to: 'pages#flexible', as: :flexible
  get 'why-simplifly', to: 'pages#why_simplifly', as: :why_simplifly
  get 'financing', to: 'pages#financing', as: :financing
  get 'pilot-training-pricing-calculator', to: 'pages#cost' 
  get 'approximate-pilot-training-costs', to: 'pages#cost', as: :cost
  get 'timeline-to-be-a-pilot', to: 'pages#timeline', as: :timeline
  get 'multi-engine-rating', to: 'pages#multi', as: :multi
  get 'commercial-pilot-training', to: 'pages#commercial', as: :commercial
  get 'instrument-rating', to: 'pages#instrument', as: :instrument
  get 'private-pilot-training', to: 'pages#private_pilot', as: :private_pilot
  get 'pilot-training', to: 'pages#pilot_training', as: :pilot_training
  get 'airline-pilot-courses', to: 'pages#airline_pilot_courses', as: :airline_pilot_courses
  #get 'pilot-programs', to: 'pages#pilot_programs', as: :programs
  get 'our-team', to: 'pages#our_team', as: :our_team
  get 'terms-of-service-privacy-policy', to: 'pages#tos', as: :tos
  #get 'aircraft-rental', to: 'pages#aircraft_rental', as: :aircraft_rental
  get 'fixed-wing-airplane-fleet', to: 'pages#fixed_wing', as: :fixed_wing
  #get 'rotary-wing-helicopter-fleet', to: 'pages#rotary_wing', as: :rotary_wing
  #get 'airplane-pilot-training', to: 'pages#airplane_training', as: :airplane_training
  #get 'helicopter-pilot-training', to: 'pages#helicopter_training', as: :helicopter_training
  get 'about-ideal-aviation', to: 'pages#about_us', as: :about_us
  #get 'advanced_training', to: 'pages#advanced_training', as: :advanced_training
  #get 'pilot-resources', to: 'pages#pilot_resources', as: :pilot_resources
  #get 'careers', to: 'pages#careers', as: :careers
  
  #new
  get 'fashion-team', to: 'pages#fashion', as: :fashion

  # Previous Site's Routes
  #get 'home/flight-training', to: 'pages#why_simplifly'
  #get 'program-pricing', to: 'pages#cost'
  #get 'programs', to: 'pages#pilot_training'
  get 'book-a-flight', to: 'discover_flights#new'
  #get 'locations', to: 'messages#location'
  get 'contact-us', to: 'messages#new'
  #get 'simplifying-your-training', to: 'pages#why_simplifly'
  #get 'flight-instructors', to: 'pages#our_team'
  #get 'category/pilot', to: 'pages#airline_pilot_courses'
  get 'becoming-a-pilot-timeline', to: 'pages#timeline'
  #get 'private-pilots-license', to: 'pages#private_pilot'
end

app/models/discover_flight.rb
class DiscoverFlight < ApplicationRecord
  before_validation :strip_phone_number
  #after_save :to_lacrm  ### NOT NEEDED.  For Ideal Aviation or flight schools that use LACRM
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true, format: { with: /\A\d{10}\z/, message: "must be a valid 10-digit phone number" }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }

  def strip_phone_number
    self.phone = phone.to_s.gsub(/[-() ]/, "")
  end

  def to_lacrm
    api_key = ENV['LACRM_API']
    # Set the endpoint and headers
    endpoint = "https://api.lessannoyingcrm.com/v2/"
    headers = {
      "Authorization" => api_key,
      "Content-Type" => "application/json"
    }
    # Get the user ID
    user_payload = {
      "Function" => "GetUser",
      "Parameters" => {}
    }
    user_response = HTTParty.get(endpoint, headers: headers, body: user_payload.to_json)
    if user_response.code == 200
      user_id = JSON.parse(user_response.body)['UserId']
    else
      # Handle the error
      user_id = nil
    end

    # Create the contact
    contact_payload = {
      "Function" => "CreateContact",
      "Parameters" => {
        "IsCompany" => false,
        "AssignedTo" => user_id,  #need to just get the USER ID so I can avoid doin the get call each time..
        "Name" => "#{self.first_name} #{self.last_name}",
        "Email" => "#{self.email}",
        "Phone" => "#{self.phone}",
        "Background Info" => "Originated from discovery flight form on website",
      }
    }


    

    response = HTTParty.post(endpoint, headers: headers, body: contact_payload.to_json)
    contact_id = JSON.parse(response.body)['ContactId']
    

    # Add a note
    note_payload = {
      "Function" => "CreateNote",
      "Parameters" => {
        "ContactId" => contact_id,
        "Note" => "
          Select aircraft category:  #{self.aircraft}
    
          Is there anything else you'd like us to know: #{self.comments}
        
          Selected Date: #{self.preferred_date}
          Selected Time: #{self.preferred_availability}
          Alternate Date: #{self.alternate_date}
          Alternate Time: #{self.alternate_availability}
        ",
      }
    }
    HTTParty.post(endpoint, headers: headers, body: note_payload.to_json)

  end  
end

app/controllers/discover_flights_controller.rb
class DiscoverFlightsController < ApplicationController
  before_action :set_discover_flight, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:create, :new, :confirmation]
  invisible_captcha only: [:create], honeypot: :confirm_email

  # GET /discover_flights or /discover_flights.json
  def index
    @discover_flights = DiscoverFlight.all
  end

  # GET /discover_flights/1 or /discover_flights/1.json
  def show
  end

  # GET /discover_flights/new
  def new
    @discover_flight = DiscoverFlight.new
  end

  # GET /discover_flights/1/edit
  def edit
  end

  # POST /discover_flights or /discover_flights.json
  def create
    @discover_flight = DiscoverFlight.new(discover_flight_params)

    respond_to do |format|
      if @discover_flight.save
        #DiscoverFlightsMailer.discover_flights_email(@discover_flight).deliver_later
        format.html { redirect_to discovery_confirmation_path, notice: "#{@discover_flight.first_name}" }
        format.json { render :show, status: :created, location: @discover_flight }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @discover_flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discover_flights/1 or /discover_flights/1.json
  #def update
  #  respond_to do |format|
  #    if @discover_flight.update(discover_flight_params)
  #      format.html { redirect_to discover_flight_url(@discover_flight), notice: "Discover flight was successfully updated." }
  #      format.json { render :show, status: :ok, location: @discover_flight }
  #    else
  #      format.html { render :edit, status: :unprocessable_entity }
  #      format.json { render json: @discover_flight.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /discover_flights/1 or /discover_flights/1.json
  def destroy
    @discover_flight.destroy

    respond_to do |format|
      format.html { redirect_to discover_flights_url, notice: "Discover flight was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discover_flight
      @discover_flight = DiscoverFlight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def discover_flight_params
      params.require(:discover_flight).permit(:first_name, :last_name, :email, :phone, :aircraft, :preferred_date, :preferred_availability, :alternate_date, :alternate_availability, :comments)
    end
end

app/helpers/discover_flights_helper.rb
module DiscoverFlightsHelper
end

app/views/discover_flights/_discover_flight.html.erb
<div id="<%= dom_id discover_flight %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">First name:</strong>
    <%= discover_flight.first_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Last name:</strong>
    <%= discover_flight.last_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= discover_flight.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone:</strong>
    <%= discover_flight.phone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Aircraft:</strong>
    <%= discover_flight.aircraft %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Preferred date:</strong>
    <%= discover_flight.preferred_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Preferred availability:</strong>
    <%= discover_flight.preferred_availability %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Alternate date:</strong>
    <%= discover_flight.alternate_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Alternate availability:</strong>
    <%= discover_flight.alternate_availability %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Comments:</strong>
    <%= discover_flight.comments %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this discover flight", discover_flight, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this discover flight', edit_discover_flight_path(discover_flight), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/discover_flights/_formARCHIVED.html.erb
<%= form_with(model: discover_flight, class: "contents") do |form| %>
  <% if discover_flight.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(discover_flight.errors.count, "error") %> prohibited this discover_flight from being saved:</h2>

      <ul>
        <% discover_flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%#= PAGE 1%>
  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :aircraft %>
    <%= form.text_field :aircraft, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <%#= BUTTON FOR NEXT PAGE %>


  <%#= PAGE 2%>
  <div class="my-5">
    <%= form.label :preferred_date %>
    <%= form.date_field :preferred_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :preferred_availability %>
    <%= form.text_field :preferred_availability, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <%#= BUTTONS FOR NEXT PAGE AND PREVIOUS PAGE %>

  <%#= PAGE 3%>
  <div class="my-5">
    <%= form.label :alternate_date %>
    <%= form.date_field :alternate_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :preferred_availability %>
    <%= form.text_field :preferred_availability, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :comments %>
    <%= form.text_area :comments, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/discover_flights/_formTEST.html.erb
<div x-data="{ currentPage: 1 }">
  
    <div x-show="currentPage === 1">
      <div class="my-5">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="inline">
        <button x-on:click="currentPage = 2" class="rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer">Next</button>
      </div>
    </div>

    <div x-show="currentPage === 2">
      <%= form.label :preferred_date %>
      <%= form.date_field :preferred_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>

      <div class="flex justify-between">
        <button class="rounded-lg py-3 px-5 bg-gray-300 text-white inline-block font-medium cursor-pointer" @click="currentPage--" :disabled="currentPage === 1">Previous</button>
        <button class="rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" @click="currentPage++">Next</button>
      </div>
    </div>

    <div x-show="currentPage === 3">
      <%= form.label :alternate_date %>
      <%= form.date_field :alternate_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>

      <div class="my-5">
        <%= form.label :comments %>
        <%= form.text_area :comments, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="flex justify-between">
        <button class="rounded-lg py-3 px-5 bg-gray-300 text-white inline-block font-medium cursor-pointer" @click="currentPage--">Previous</button>
        <div class="inline">
          <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/discover_flights/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing discover flight</h1>

  <%= render "form", discover_flight: @discover_flight %>

  <%= link_to "Show this discover flight", @discover_flight, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to discover flights", discover_flights_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/discover_flights/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Discover flights</h1>
    <%= link_to 'New discover flight', new_discover_flight_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="discover_flights" class="min-w-full">
    <%= render @discover_flights %>
  </div>
</div>

app/views/discover_flights/new.html.erb
<%# Head / Meta Data %>
<% title("Discovery Flight | BlueBird Aviation Academy") %>
<% meta_description("Experience the thrill of aviation with a discovery flight at BlueBird in Mesa, Phoenix, Scottsdale, and Spanish Fork, Salt Lake. Take the controls and get a taste of what it's like to be a pilot.") %>
<% meta_keywords("Discovery Flight, Introductory Flight, Flight Experience, Marthasville Flight School, Phoenix Flight School, Scottsdale Flight School, Spanish Fork Flight School, Salt Lake Flight School") %>

<header class="w-full bg-home bg-aerial h-screen lg:h-screen bg-cover bg-center flex justify-center items-center" id="top">
  <div class="px-5 py-40 lg:py-52 flex flex-col justify-center items-start w-full">
      <h1 class="font-semibold text-6xl text-center lg:text-start font-header uppercase text-white">Book a Discovery Flight</h1>
      <h2 class="font-bold text-4xl text-center lg:text-start py-10 text-sky-500">Fly at BlueBird and See if Flying is for You</h2>
      <div class="w-full flex flex-col items-center lg:hidden">
        <a href="#quiz-frame", class="btn-primary"
          onclick="event.preventDefault(); document.getElementById('quiz-frame').scrollIntoView({ behavior: 'smooth' });">
          FLY NOW
        </a>
      </div>
  </div>
</header>

<turbo-frame id="quiz-frame">
  <div class=" lg:absolute right-5 top-10 z-50 bg-white lg:rounded-xl lg:w-1/4 border pb-5 lg:overflow-y-auto lg:h-[92vh]">
    <%#= render "form", discover_flight: @discover_flight %>
    <div class="calendly-inline-widget" data-url="https://calendly.com/simpliflyflightschool?hide_gdpr_banner=1" style="height:630px;"></div>
    <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
  </div>
</turbo-frame>

<div class="flex flex-col items-center">
  <div class="lg:w-1/2 lg:px-10">
    <h3 class="font-semibold text-4xl py-10 text-center uppercase font-header">What to Expect</h3>
    <p class="p-text px-5 pb-5">
      Your Discovery Flight is designed to give you a taste of what it's like to be a pilot. You'll spend approximately 60 minutes in the air with one of our certified flight instructors, who will guide you through the basics of flying and answer any questions you may have. You'll also have the opportunity to take the controls and experience the thrill of flying first hand.
    </p>
    <p class="p-text px-5 pb-5">
      During your discovery flight, you'll sit in the pilot seat and the FAA Certified Flight Instructor at your side will allow you to fly for the majority of the flight. A discovery flight is a great option if you’re considering a career in aviation, a new hobby or it can make a unique gift for anyone at any age. You can even bring a friend to ride along. At the end of the flight, the instructor will be able to answer any questions that you may have.
    </p>
    <h3 class="font-semibold text-4xl py-10 text-center uppercase font-header">What Happens After the Flight?</h3>
    <p class="p-text px-5 pb-5">
      So, you've completed your discovery flight and are ready to take the next step? BlueBird is here to help you take flight towards your aviation dreams and attain your goals.  Let's dive into what happens after your first flight with us.  
    </p>

    <div class="bg-white max-w-xl mx-5 lg:mx-auto border border-gray-200 rounded-2xl mb-10">
      <ul class="shadow-box">					
        <li class="relative border-b border-gray-200" x-data="{selected:null}">
          <button type="button" class="w-full px-8 py-6 text-left" @click="selected !== 1 ? selected = 1 : selected = null">
            <div class="flex items-center justify-between">
              <span class="font-semibold text-lg">Work with our team to create a plan</span>
              <span class="ico-plus"></span>
            </div>
          </button>
          <div class="relative overflow-hidden transition-all max-h-0 duration-700" style="" x-ref="container1" x-bind:style="selected == 1 ? 'max-height: ' + $refs.container1.scrollHeight + 'px' : ''">
            <div class="p-6 p-text">
              <p>Our team will pair you with a certified flight instructor (CFI) who will work with you to create a personalized plan that fits your schedule and goals. Together, you will establish a flight training schedule, review the syllabus, and discuss any questions or concerns you may have.</p>
            </div>
          </div>
        </li>
        <li class="relative border-b border-gray-200" x-data="{selected:null}">
          <button type="button" class="w-full px-8 py-6 text-left" @click="selected !== 2 ? selected = 2 : selected = null">
            <div class="flex items-center justify-between">
              <span class="font-semibold text-lg">Take care of the prerequisites</span>
              <span class="ico-plus"></span>
            </div>
          </button>
          <div class="relative overflow-hidden transition-all max-h-0 duration-700" style="" x-ref="container2" x-bind:style="selected == 2 ? 'max-height: ' + $refs.container2.scrollHeight + 'px' : ''">
            <div class="p-6 p-text">
              <p>Before you can start your flight training, you will need to complete a medical exam, purchase your books, and work on completing your ground school and written exam. Our team will be with you every step of the way to ensure you have everything you need to succeed.</p>
            </div>
          </div>
        </li>
        <li class="relative border-b border-gray-200" x-data="{selected:null}">
          <button type="button" class="w-full px-8 py-6 text-left" @click="selected !== 3 ? selected = 3 : selected = null">
            <div class="flex items-center justify-between">
              <span class="font-semibold text-lg">Start flight training and ground school</span>
              <span class="ico-plus"></span>
            </div>
          </button>
          <div class="relative overflow-hidden transition-all max-h-0 duration-700" style="" x-ref="container3" x-bind:style="selected == 3 ? 'max-height: ' + $refs.container3.scrollHeight + 'px' : ''">
            <div class="p-6 p-text">
              <p>Once you have completed your prerequisites, it's time to start building your flight hours and experience. You will work with your CFI to complete flight lessons and ground school, mastering the skills needed to become a proficient pilot.</p>
            </div>
          </div>
        </li>
        <li class="relative border-b border-gray-200" x-data="{selected:null}">
          <button type="button" class="w-full px-8 py-6 text-left" @click="selected !== 4 ? selected = 4 : selected = null">
            <div class="flex items-center justify-between">
              <span class="font-semibold text-lg">Pass your checkride</span>
              <span class="ico-plus"></span>
            </div>
          </button>
          <div class="relative overflow-hidden transition-all max-h-0 duration-700" style="" x-ref="container4" x-bind:style="selected == 4 ? 'max-height: ' + $refs.container4.scrollHeight + 'px' : ''">
            <div class="p-6 p-text">
              <p>As you near the end of your flight training, you will work with your CFI to prepare for your check ride. Our team will ensure that you are well-prepared and confident.  We'll have stage checks along the way so you can successfully pass your check ride and earn your pilot's license.</p>
            </div>
          </div>
        </li>
        <li class="relative " x-data="{selected:null}">
          <button type="button" class="w-full px-8 py-6 text-left" @click="selected !== 5 ? selected = 5 : selected = null">
            <div class="flex items-center justify-between">
              <span class="font-semibold text-lg">Enjoy flying and continue your aviation journey</span>
              <span class="ico-plus"></span>
            </div>
          </button>
          <div class="relative overflow-hidden transition-all max-h-0 duration-700" style="" x-ref="container5" x-bind:style="selected == 5 ? 'max-height: ' + $refs.container5.scrollHeight + 'px' : ''">
            <div class="p-6 p-text">
              <p>Congratulations, you are now a certified pilot! Your aviation journey doesn't have to end here though. Our team can help you continue to improve your skills and earn additional ratings, such as an instrument rating or commercial certificate. Whether you want to fly for fun or pursue a career in aviation, we are here to support you every step of the way.</p>
            </div>
          </div>
        </li>
      </ul>
    </div>

    <div class="pt-10 flex flex-row gap-3 justify-center">
      <%= link_to pilot_training_path do %>
        <div class="btn-secondary mb-10">
          VIEW PROGRAMS
        </div>
      <% end %>
      <a href="#top", class="hidden lg:block"
        onclick="event.preventDefault(); document.getElementById('top').scrollIntoView({ behavior: 'smooth' });">
        <div class="btn-primary mb-10 border-2 border-sky-500 hover:border-sky-600 lg:px-16">
        FLY NOW
        </div>
      </a>
      <a href="#quiz-frame", class="lg:hidden"
        onclick="event.preventDefault(); document.getElementById('quiz-frame').scrollIntoView({ behavior: 'smooth' });">
        <div class="btn-primary mb-10 border-2 border-sky-500 hover:border-sky-600 lg:px-16">
        FLY NOW
        </div>
      </a>
    </div>
  </div>
</div>

<div class="hidden lg:block px-2 bg-sky-200">
  <%= render "shared/bottom_footer"%>
</div>

<div class="lg:hidden w-full bg-sky-200 pt-16 pb-5 pl-5">
  <%= render "shared/bottom_footer"%>
</div>

app/views/discover_flights/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @discover_flight %>

    <%= link_to 'Edit this discover_flight', edit_discover_flight_path(@discover_flight), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this discover_flight', discover_flight_path(@discover_flight), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to discover_flights', discover_flights_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>