config/routes.rb
Rails.application.routes.draw do

    # 404/500 pages
    get 'errors/not_found'
    get 'errors/internal_server_error'
    match "/404", to: "errors#not_found", via: :all
    match "/500", to: "errors#internal_server_error", via: :all
  
  #devise_scope :admins do
  #  # Redirests signing out users back to sign-in
  #  get "admins", to: "devise/sessions#new"
  #end

  devise_for :admins, controllers: { registrations: "registrations", sessions: "sessions" }
  root "pages#home"   #---- UNCOMMENT For HOME PAGE.
  #root "pages#template_start"  # --- Hello World Home page

  #post 'uploader/image', to: 'uploader#image' #add upload image to posts 
  get 'blog', to: 'posts#index', as: :blog
  #resources :posts
  
  #resources :discover_flights
  #resources :messages
  #resources :enrollments
  #resources :book_downloads
  #resources :checkouts
  #resources :quiz_results

  # Enrollment form
  get 'enroll-at-simplifly', to: 'enrollments#new', as: :enroll
  get 'enrollment-confirmation', to: 'enrollments#confirmation', as: :enroll_confirmation

  # Contact form
  get 'contact', to: 'messages#new', as: :contact
  get 'contact-confirmation', to: 'messages#confirmation', as: :contact_confirmation
  get 'visit-simplifly', to: 'messages#location', as: :location
  get 'instruct-at-simplifly', to: 'messages#cfi', as: :cfi

  # Book Download
  get 'book-download-confirmation', to: 'book_downloads#confirmation', as: :book_download_confirmation

  # Discovery flight form
  get 'discovery-flight', to: 'discover_flights#new', as: :discovery_flight
  get 'discovery-flight-confirmation', to: 'discover_flights#confirmation', as: :discovery_confirmation

  # Check out form
  #get 'rental-checkout', to: 'checkouts#new', as: :rental_checkout
  #get 'rental-checkout-confirmation', to: 'checkouts#confirmation', as: :checkout_confirmation

  # Quiz form
  #get 'quiz', to: 'quiz_results#new', as: :quiz
  #get 'quiz-confirmation', to: 'quiz_results#confirmation', as: :quiz_confirmation

  # Static Pages
  get 'stratus-finance', to: 'pages#stratus', as: :stratus
  get 'meritize', to: 'pages#meritize', as: :meritize
  get 'accelerated-pilot-training', to: 'pages#accelerated', as: :accelerated
  get 'flexible-pilot-training', to: 'pages#flexible', as: :flexible
  get 'why-simplifly', to: 'pages#why_simplifly', as: :why_simplifly
  get 'financing', to: 'pages#financing', as: :financing
  get 'pilot-training-pricing-calculator', to: 'pages#cost' 
  get 'approximate-pilot-training-costs', to: 'pages#cost', as: :cost
  get 'timeline-to-be-a-pilot', to: 'pages#timeline', as: :timeline
  get 'multi-engine-rating', to: 'pages#multi', as: :multi
  get 'commercial-pilot-training', to: 'pages#commercial', as: :commercial
  get 'instrument-rating', to: 'pages#instrument', as: :instrument
  get 'private-pilot-training', to: 'pages#private_pilot', as: :private_pilot
  get 'pilot-training', to: 'pages#pilot_training', as: :pilot_training
  get 'airline-pilot-courses', to: 'pages#airline_pilot_courses', as: :airline_pilot_courses
  #get 'pilot-programs', to: 'pages#pilot_programs', as: :programs
  get 'our-team', to: 'pages#our_team', as: :our_team
  get 'terms-of-service-privacy-policy', to: 'pages#tos', as: :tos
  #get 'aircraft-rental', to: 'pages#aircraft_rental', as: :aircraft_rental
  get 'fixed-wing-airplane-fleet', to: 'pages#fixed_wing', as: :fixed_wing
  #get 'rotary-wing-helicopter-fleet', to: 'pages#rotary_wing', as: :rotary_wing
  #get 'airplane-pilot-training', to: 'pages#airplane_training', as: :airplane_training
  #get 'helicopter-pilot-training', to: 'pages#helicopter_training', as: :helicopter_training
  get 'about-ideal-aviation', to: 'pages#about_us', as: :about_us
  #get 'advanced_training', to: 'pages#advanced_training', as: :advanced_training
  #get 'pilot-resources', to: 'pages#pilot_resources', as: :pilot_resources
  #get 'careers', to: 'pages#careers', as: :careers
  
  #new
  get 'fashion-team', to: 'pages#fashion', as: :fashion

  # Previous Site's Routes
  #get 'home/flight-training', to: 'pages#why_simplifly'
  #get 'program-pricing', to: 'pages#cost'
  #get 'programs', to: 'pages#pilot_training'
  get 'book-a-flight', to: 'discover_flights#new'
  #get 'locations', to: 'messages#location'
  get 'contact-us', to: 'messages#new'
  #get 'simplifying-your-training', to: 'pages#why_simplifly'
  #get 'flight-instructors', to: 'pages#our_team'
  #get 'category/pilot', to: 'pages#airline_pilot_courses'
  get 'becoming-a-pilot-timeline', to: 'pages#timeline'
  #get 'private-pilots-license', to: 'pages#private_pilot'
end

app/views/shared/_admin_menu.html.erb
<div x-data="{ usermenu: false }" class="font-mono ">
  <div class="w-full lg:h-10 h-16 bg-slate-700 flex flex-row justify-between items-center sticky z-50">
    <div class="pl-5 text-slate-100">
      Welcome, admin <%#= current_admin.email %>
    </div>

    <!--Hamburger button-->
    <button @click="usermenu = ! usermenu;" class="text-slate-500 text-4xl pr-5 pb-1 hover:text-slate-800 lg:hidden">
      ☰
    </button>
    
    <!--desktop menu-->
    <div class="hidden lg:flex lg:flex-row lg:pr-10 xl:pr-5">
      <!--Button-->
      <%= button_to 'New Post', new_post_path, method: :get, data: { turbo: false }, class: "text-center block mr-5 text-slate-200 rounded-lg hover:underline" %>
      <%= button_to 'Sign Out', destroy_admin_session_path, method: :delete, class: "text-center block mr-5 text-slate-200 rounded-lg hover:underline" %>
    </div>
  </div>

    <!--Mobile Menu--->
    <div x-cloak x-show="usermenu" x-transition.duration.200ms class="bg-slate-700 flex flex-col justify-start items-center pb-10 z-50">
      <!--Spacer-->
      <div class="h-12"></div>
      <%= button_to 'New Post', new_post_path, method: :get, data: { turbo: false }, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>
      <%= button_to 'Sign Out', destroy_admin_session_path, method: :delete, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>

    <!--Close button-->
    <button @click="usermenu = ! usermenu;" class="leading-10 text-slate-100 hover:text-slate-400 hover:bg-slate-700 border-2 hover:border-slate-400 w-min mt-5 px-5 rounded-full py-1">
      X
    </button>

    </div>
  </div>

app/views/shared/_after_discovery.html.erb
<section class="bg-gradient-to-t from-slate-50 to-blue-100 py-10">
  <h2 class="text-3xl font-semibold pb-10 font-sans mx-5 text-center">What happens after the discovery flight?</h2>
  <div class=" max-w-2xl mx-5 lg:mx-auto p-text pb-12">
    So, you've completed your discovery flight and are ready to take the next step? Ideal Aviation is here to help you take flight towards your aviation dreams and attain your goals.  Let's dive into what happens after your first flight with us.  
  </div>

  <div class="bg-white max-w-xl mx-5 lg:mx-auto border border-gray-200 rounded-2xl mb-10">
		<ul class="shadow-box">					
		  <li class="relative border-b border-gray-200" x-data="{selected:null}">
			  <button type="button" class="w-full px-8 py-6 text-left" @click="selected !== 1 ? selected = 1 : selected = null">
				  <div class="flex items-center justify-between">
					  <span class="font-semibold text-lg">Work with our team to create a plan</span>
					  <span class="ico-plus"></span>
				  </div>
        </button>
			  <div class="relative overflow-hidden transition-all max-h-0 duration-700" style="" x-ref="container1" x-bind:style="selected == 1 ? 'max-height: ' + $refs.container1.scrollHeight + 'px' : ''">
				  <div class="p-6 p-text">
					  <p>Our team will pair you with a certified flight instructor (CFI) who will work with you to create a personalized plan that fits your schedule and goals. Together, you will establish a flight training schedule, review the syllabus, and discuss any questions or concerns you may have.</p>
				  </div>
			  </div>
		  </li>
		  <li class="relative border-b border-gray-200" x-data="{selected:null}">
			  <button type="button" class="w-full px-8 py-6 text-left" @click="selected !== 2 ? selected = 2 : selected = null">
				  <div class="flex items-center justify-between">
					  <span class="font-semibold text-lg">Take care of the prerequisites</span>
					  <span class="ico-plus"></span>
				  </div>
				</button>
			  <div class="relative overflow-hidden transition-all max-h-0 duration-700" style="" x-ref="container2" x-bind:style="selected == 2 ? 'max-height: ' + $refs.container2.scrollHeight + 'px' : ''">
				  <div class="p-6 p-text">
					  <p>Before you can start your flight training, you will need to complete a medical exam, purchase your books, and work on completing your ground school and written exam. Our team will be with you every step of the way to ensure you have everything you need to succeed.</p>
				  </div>
			  </div>
		  </li>
      <li class="relative border-b border-gray-200" x-data="{selected:null}">
			  <button type="button" class="w-full px-8 py-6 text-left" @click="selected !== 3 ? selected = 3 : selected = null">
				  <div class="flex items-center justify-between">
					  <span class="font-semibold text-lg">Start flight training and ground school</span>
					  <span class="ico-plus"></span>
				  </div>
				</button>
			  <div class="relative overflow-hidden transition-all max-h-0 duration-700" style="" x-ref="container3" x-bind:style="selected == 3 ? 'max-height: ' + $refs.container3.scrollHeight + 'px' : ''">
				  <div class="p-6 p-text">
					  <p>Once you have completed your prerequisites, it's time to start building your flight hours and experience. You will work with your CFI to complete flight lessons and ground school, mastering the skills needed to become a proficient pilot.</p>
				  </div>
			  </div>
		  </li>
      <li class="relative border-b border-gray-200" x-data="{selected:null}">
			  <button type="button" class="w-full px-8 py-6 text-left" @click="selected !== 4 ? selected = 4 : selected = null">
				  <div class="flex items-center justify-between">
					  <span class="font-semibold text-lg">Pass your checkride</span>
					  <span class="ico-plus"></span>
				  </div>
				</button>
			  <div class="relative overflow-hidden transition-all max-h-0 duration-700" style="" x-ref="container4" x-bind:style="selected == 4 ? 'max-height: ' + $refs.container4.scrollHeight + 'px' : ''">
				  <div class="p-6 p-text">
					  <p>As you near the end of your flight training, you will work with your CFI to prepare for your check ride. Our team will ensure that you are well-prepared and confident.  We'll have stage checks along the way so you can successfully pass your check ride and earn your pilot's license.</p>
				  </div>
			  </div>
		  </li>
      <li class="relative " x-data="{selected:null}">
        <button type="button" class="w-full px-8 py-6 text-left" @click="selected !== 5 ? selected = 5 : selected = null">
          <div class="flex items-center justify-between">
            <span class="font-semibold text-lg">Enjoy flying and continue your aviation journey</span>
            <span class="ico-plus"></span>
          </div>
        </button>
        <div class="relative overflow-hidden transition-all max-h-0 duration-700" style="" x-ref="container5" x-bind:style="selected == 5 ? 'max-height: ' + $refs.container5.scrollHeight + 'px' : ''">
          <div class="p-6 p-text">
            <p>Congratulations, you are now a certified pilot! Your aviation journey doesn't have to end here though. Our team can help you continue to improve your skills and earn additional ratings, such as an instrument rating or commercial certificate. Whether you want to fly for fun or pursue a career in aviation, we are here to support you every step of the way.</p>
          </div>
        </div>
      </li>
    </ul>
	</div>

  <div class=" max-w-2xl mx-5 lg:mx-auto p-text pb-10 flex flex-col items-center">
    At Ideal Aviation, we are passionate about aviation and sharing the joy of flying with others. Don't procrastinate. Contact us today to get started on your aviation journey.
      <%=link_to contact_path, data: { turbo: false }, class: "mx-auto" do%>
        <div class="btn-primary mt-5">
          CONTACT US
        </div>
      <% end %>
  </div>

</section>

app/views/shared/_cta_were_experts.html.erb
<section class="w-full bg-ideal-ramp bg-cover h-screen-3/4 lg:h-screen-4/5 bg-[center_right_-3rem] flex justify-center items-center">
  <div class="flex flex-col justify-center items-center drop-shadow-2xl transform-gpu" x-data>
    <h2 class="w-4/5 font-bold text-5xl lg:text-7xl">We are the <span class="text-ideal-blue">flight training experts</span> of St. Louis</h2>
    <p class="w-4/5 py-5 lg:py-10 text-xl lg:text-2xl font-semibold">The Ideal Aviation family comes from a long history of aviation in St. Louis.  Dating back to the 1980's Ideal Aviation has been helping pilots earn their wings.</p>
    <div class="opacity-0 duration-[1500ms] translate-y-24 text-center w-full flex flex-col items-start" x-intersect="$el.classList.add('opacity-100', 'translate-y-1', 'z-0')">
      <%=link_to location_path, data: { turbo: false }, class: "mx-auto" do%>
        <div class="btn-primary text-xl lg:text-3xl">
          VISIT IDEAL TODAY
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/shared/_finance.html.erb
<div class="flex flex-col items-center">
  <div class="pt-10">
    <h2 class="text-xl font-semibold italic text-center px-16">BlueBird Best has partnered with the following companies to help our students fund their pilot training</h2>
  </div>
  <div class="flex flex-col lg:flex-row justify-center items-center gap-10 lg:gap-20 px-20 md:px-48  lg:px-5 pt-10 pb-20 lg:py-10">
    <!--STRATUS-->
    <%= link_to stratus_path, class: "lg:w-1/5" do %>
      <%= image_tag "stratus_logo.webp", alt: "Stratus Financial logo", class: "hover:scale-105 transition-all duration-300"%>
    <%end%>
    
    <!--Meritize-->
    <%= link_to meritize_path, class: "lg:w-1/6" do %>
      <%= image_tag "meritize.webp", alt: "Meritize logo", class: "hover:scale-105 transition-all duration-300"%>
    <%end%>
    
    <!--Flight training finance-->
    <%= link_to "https://www.flighttrainingfinancellc.com", class: "lg:w-1/5", target: :blank do %>
      <%= image_tag "flight-training-finance.webp", alt: "Flight Training Finance logo", class: "hover:scale-105 transition-all duration-300 rounded-xl"%>
    <%end%>
    <!--AOPA-->
    <%= link_to "https://finance.aopa.org", class: "", target: :blank do %>
      <%= image_tag "aopa.webp", alt: "AOPA logo", class: "hover:scale-105 transition-all duration-300"%>
    <%end%>
  </div>
</div>
<div class="py-10 w-full grid place-items-center">
  <%= link_to "VIEW FINANCING", financing_path, data: { turbo: false }, class: "btn-primary" %>
</div>

app/views/shared/_guarantee.html.erb
<section class="flex flex-col items-center pb-10">
  <div class="max-w-4xl flex flex-col pt-10 px-5">
    <h3 class="text-5xl font-header uppercase font-semibold pt-20 pb-5">The BlueBird Best Guarantee</h3>
    <p class="text-lg pb-10">When you complete your <%= link_to "private", private_pilot_path, class: "text-sky-600 hover:underline", data: {turbo: false}%>, <%= link_to "instrument", instrument_path, class: "text-sky-600 hover:underline", data: {turbo: false}%>, <%= link_to "commercial", commercial_path, class: "text-sky-600 hover:underline", data: {turbo: false}%>, and <%= link_to "CFI", cfi_path, class: "text-sky-600 hover:underline", data: {turbo: false}%> training at BlueBird Best, we have an exciting opportunity for you. As a testament to our confidence in your abilities, we offer a guaranteed interview for a teaching position as a CFI within our flight school. This exclusive opportunity allows you to showcase the knowledge and skills you have acquired during your training journey with us. Join our team of dedicated instructors, inspire future aviators, and make a meaningful impact in the aviation community. Take the next step in your career as a CFI with SimpliFly and let your passion for aviation soar.</p>
  </div>
  <div class="flex gap-5">
    <%= link_to "APPLY TO BE A CFI", cfi_path,  target: "blank", data: { turbo: false }, class: "btn-primary" %>
</section>

app/views/shared/_header_nav_mobile_menusimplify.html.erb
<!--Hamburger Button-->
<button x-on:click="open = !open"
        class="flex items-center space-x-2 focus:outline-none">

  <span x-text="open ? 'Close' : 'Menu'"
        class="text-lg font-semibold ">Menu</span>
  
  <div class="w-6 flex items-center justify-center relative text-white">
    <span x-bind:class="open ? 'translate-y-0 rotate-45' : '-translate-y-2'"
          class="transform transition duration-500 w-full h-[3px] bg-current absolute"></span>
    
    <span x-bind:class="open ? 'opacity-0 translate-x-3' : 'opacity-100'"
          class="transform transition duration-500 w-full h-[3px] bg-current absolute"></span>
    
    <span x-bind:class="open ? 'translate-y-0 -rotate-45' : 'translate-y-2'"
          class="transform transition duration-500 w-full h-[3px] bg-current absolute"></span>
  </div>
</button>

<menu x-show="open"
      x-cloak
      x-transition:enter="transition ease-out duration-300 transform"
      x-transition:enter-start="-translate-x-full opacity-0"
      x-transition:enter-end="translate-x-0 opacity-100"
      x-transition:leave="transition ease-in duration-300 transform"
      x-transition:leave-start="translate-x-0 opacity-100"
      x-transition:leave-end="-translate-x-full opacity-0"
      class="absolute h-screen-mobile font-header text-xl overflow-y-auto w-screen left-0 top-16 bg-gradient-to-b from-sky-600/90 to-sky-100 pt-10 flex flex-col z-30"
>
  <div class="ml-16 mr-5 mt-5" x-data="{
          mobile_resources_drop: false,
          mobile_now_drop: false,
          mobile_certification_drop: false,
          mobile_about_drop: false }">
    <ul class="space-y-4 font-semibold">
      <li><%= link_to "ENROLL TODAY", enroll_path, target: "blank", data: { turbo: false }%></li>
      <li><%= link_to "DISCOVERY FLIGHT", discovery_flight_path, target: "blank", data: { turbo: false }%></li>
      <li>
        <div class="flex flex-row justify-between" >
          <div class=""><%= link_to "HOW TO BECOME A PILOT", root_path, data: { turbo: false }%></div>
          <div class="px-5 py-1" x-on:click="mobile_resources_drop = ! mobile_resources_drop">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="transition-transform duration-500 ease-in-out" viewBox="0 0 16 16" x-bind:class="{ 'rotate-[90deg]': mobile_resources_drop }">
              <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
            </svg>
          </div>
        </div>
      </li>
        <!--Drop Down-->
        <li class="ml-5 animate-slide-in-left" x-show="mobile_resources_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left': !mobile_resources_drop}">
          <%= link_to "DISCOVERY FLIGHT" , discovery_flight_path, data: { turbo: false }, target: "blank"%>
        </li>
        <li class="ml-5 animate-slide-in-left2" x-show="mobile_resources_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left2': !mobile_resources_drop}">
          <%= link_to "ENROLL AT SIMPLIFLY", enroll_path, target: "blank", data: { turbo: false }%>
        </li>
        <li class="ml-5 animate-slide-in-left3" x-show="mobile_resources_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left2': !mobile_resources_drop}">
          <%= link_to "PILOT TRAINING", pilot_training_path, target: "blank", data: { turbo: false }%>
        </li>        
        <li class="ml-5 animate-slide-in-left4" x-show="mobile_resources_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left3': !mobile_resources_drop}">
          <%= link_to "BEGIN PILOT CAREER", cfi_path, data: { turbo: false }%>
        </li>
      <li>
        <div class="flex flex-row justify-between" >
          <div class=""><%=link_to "AIRLINE PILOT COURSES", airline_pilot_courses_path, data: { turbo: false }%></div>
          <div class="px-5 py-1" x-on:click="mobile_now_drop = ! mobile_now_drop">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="transition-transform duration-500 ease-in-out" viewBox="0 0 16 16" x-bind:class="{ 'rotate-[90deg]': mobile_now_drop }">
              <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
            </svg>
          </div>
        </div>
      </li>
        <!--Drop Down-->
        <li class="ml-5 animate-slide-in-left" x-show="mobile_now_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left': !mobile_now_drop}">
          <%=link_to "ACCELERATED TRAINING", accelerated_path, data: { turbo: false }%>
        </li>
        <li class="ml-5 animate-slide-in-left2" x-show="mobile_now_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left': !mobile_now_drop}">
          <%=link_to "FLEXIBLE TRAINING", flexible_path, data: { turbo: false }%>
        </li>
        <li class="ml-5 animate-slide-in-left3" x-show="mobile_now_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left2': !mobile_now_drop}">
          <%=link_to "TIMELINE", timeline_path, data: { turbo: false }%>
        </li>
        <li class="ml-5 animate-slide-in-left4" x-show="mobile_now_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left3': !mobile_now_drop}">
          <%=link_to "COST", cost_path, data: { turbo: false }%>
        </li>
      <li>
        <div class="flex flex-row justify-between" >
          <div class=""><%= link_to "FINANCING", financing_path, data: { turbo: false }%></div>
          <div class="px-5 py-1" x-on:click="mobile_certification_drop = ! mobile_certification_drop">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="transition-transform duration-500 ease-in-out" viewBox="0 0 16 16" x-bind:class="{ 'rotate-[90deg]': mobile_certification_drop }">
              <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
            </svg>
          </div>
        </div>
      </li>
        <!--Drop Down-->
        <li class="ml-5 animate-slide-in-left" x-show="mobile_certification_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left2': !mobile_certification_drop}">
          <%=link_to "STRATUS FINANCIAL", stratus_path, data: { turbo: false }%>
        </li>
        <li class="ml-5 animate-slide-in-left2" x-show="mobile_certification_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left': !mobile_certification_drop}">
          <%=link_to "MERITIZE", meritize_path, data: { turbo: false }%>
        </li>
      <li>
        <div class="flex flex-row justify-between" >
          <div class=""><%= link_to "SIMPLIFLY", why_simplifly_path, data: { turbo: false }%></div>
          <div class="px-5 py-1" x-on:click="mobile_about_drop = ! mobile_about_drop">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="transition-transform duration-500 ease-in-out" viewBox="0 0 16 16" x-bind:class="{ 'rotate-[90deg]': mobile_about_drop }">
              <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
            </svg>
          </div>
        </div>
      </li>
        <!--Drop Down-->
        <li class="ml-5 animate-slide-in-left" x-show="mobile_about_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left': !mobile_about_drop}">
          <%=link_to "WHY SIMPLIFLY", why_simplifly_path, data: { turbo: false }%>
        </li>
        <li class="ml-5 animate-slide-in-left2" x-show="mobile_about_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left2': !mobile_about_drop}">
          <%=link_to "MEET OUR TEAM", our_team_path, data: { turbo: false }%>
        </li>
        <!--<li class="ml-5 animate-slide-in-left3" x-show="mobile_about_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left3': !mobile_about_drop}">
          <%=link_to "AIRPLANES", root_path, data: { turbo: false }%>
        </li>-->
        <li class="ml-5 animate-slide-in-left4" x-show="mobile_about_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left4': !mobile_about_drop}">
          <%=link_to "LOCATIONS", location_path, data: { turbo: false }%>
        </li>
        <li class="ml-5 animate-slide-in-left5" x-show="mobile_about_drop" x-transition x-transition:leave.duration.300ms x-bind:class="{'animate-slide-out-left5': !mobile_about_drop}">
          <%=link_to "BLOG", blog_path, data: { turbo: false }%>
        </li>
    </ul>
  </div>
</menu>

app/views/shared/_header_nav_phone.html.erb
<nav class="flex flex-row justify-center lg:justify-between items-center bg-sky-800 font-semibold text-white py-1 px-6">
<div></div>  
<div class="flex-row gap-8 text-center " >
    <h2 class="text-xl font-bold" >Best IMAGINARY Aviation School West of St. Louis Metro Area</h2>
    
  </div>
  
  
  <div class="text-xl font-extrabold hidden lg:flex ">
    <%= link_to "(314) 358-2100 ", "tel:1-314-358-2100" %>
  </div>

  <%# BACKLINK AREA #%>
  <div class="text-neutral-900 text-xs absolute z-0 overflow-hidden -left-[100rem]">
    <%= link_to "Sun City Website Designed and Developed by Right Rudder Marketing", "https://rightruddermarketing.com"%>
  </div>
</nav>