config/routes.rb
Rails.application.routes.draw do

    # 404/500 pages
    get 'errors/not_found'
    get 'errors/internal_server_error'
    match "/404", to: "errors#not_found", via: :all
    match "/500", to: "errors#internal_server_error", via: :all
  
  #devise_scope :admins do
  #  # Redirests signing out users back to sign-in
  #  get "admins", to: "devise/sessions#new"
  #end

  devise_for :admins, controllers: { registrations: "registrations", sessions: "sessions" }
  root "pages#home"   #---- UNCOMMENT For HOME PAGE.
  #root "pages#template_start"  # --- Hello World Home page

  #post 'uploader/image', to: 'uploader#image' #add upload image to posts 
  get 'blog', to: 'posts#index', as: :blog
  #resources :posts
  
  #resources :discover_flights
  #resources :messages
  #resources :enrollments
  #resources :book_downloads
  #resources :checkouts
  #resources :quiz_results

  # Enrollment form
  get 'enroll-at-simplifly', to: 'enrollments#new', as: :enroll
  get 'enrollment-confirmation', to: 'enrollments#confirmation', as: :enroll_confirmation

  # Contact form
  get 'contact', to: 'messages#new', as: :contact
  get 'contact-confirmation', to: 'messages#confirmation', as: :contact_confirmation
  get 'visit-simplifly', to: 'messages#location', as: :location
  get 'instruct-at-simplifly', to: 'messages#cfi', as: :cfi

  # Book Download
  get 'book-download-confirmation', to: 'book_downloads#confirmation', as: :book_download_confirmation

  # Discovery flight form
  get 'discovery-flight', to: 'discover_flights#new', as: :discovery_flight
  get 'discovery-flight-confirmation', to: 'discover_flights#confirmation', as: :discovery_confirmation

  # Check out form
  #get 'rental-checkout', to: 'checkouts#new', as: :rental_checkout
  #get 'rental-checkout-confirmation', to: 'checkouts#confirmation', as: :checkout_confirmation

  # Quiz form
  #get 'quiz', to: 'quiz_results#new', as: :quiz
  #get 'quiz-confirmation', to: 'quiz_results#confirmation', as: :quiz_confirmation

  # Static Pages
  get 'stratus-finance', to: 'pages#stratus', as: :stratus
  get 'meritize', to: 'pages#meritize', as: :meritize
  get 'accelerated-pilot-training', to: 'pages#accelerated', as: :accelerated
  get 'flexible-pilot-training', to: 'pages#flexible', as: :flexible
  get 'why-simplifly', to: 'pages#why_simplifly', as: :why_simplifly
  get 'financing', to: 'pages#financing', as: :financing
  get 'pilot-training-pricing-calculator', to: 'pages#cost' 
  get 'approximate-pilot-training-costs', to: 'pages#cost', as: :cost
  get 'timeline-to-be-a-pilot', to: 'pages#timeline', as: :timeline
  get 'multi-engine-rating', to: 'pages#multi', as: :multi
  get 'commercial-pilot-training', to: 'pages#commercial', as: :commercial
  get 'instrument-rating', to: 'pages#instrument', as: :instrument
  get 'private-pilot-training', to: 'pages#private_pilot', as: :private_pilot
  get 'pilot-training', to: 'pages#pilot_training', as: :pilot_training
  get 'airline-pilot-courses', to: 'pages#airline_pilot_courses', as: :airline_pilot_courses
  #get 'pilot-programs', to: 'pages#pilot_programs', as: :programs
  get 'our-team', to: 'pages#our_team', as: :our_team
  get 'terms-of-service-privacy-policy', to: 'pages#tos', as: :tos
  #get 'aircraft-rental', to: 'pages#aircraft_rental', as: :aircraft_rental
  get 'fixed-wing-airplane-fleet', to: 'pages#fixed_wing', as: :fixed_wing
  #get 'rotary-wing-helicopter-fleet', to: 'pages#rotary_wing', as: :rotary_wing
  #get 'airplane-pilot-training', to: 'pages#airplane_training', as: :airplane_training
  #get 'helicopter-pilot-training', to: 'pages#helicopter_training', as: :helicopter_training
  get 'about-ideal-aviation', to: 'pages#about_us', as: :about_us
  #get 'advanced_training', to: 'pages#advanced_training', as: :advanced_training
  #get 'pilot-resources', to: 'pages#pilot_resources', as: :pilot_resources
  #get 'careers', to: 'pages#careers', as: :careers
  
  #new
  get 'fashion-team', to: 'pages#fashion', as: :fashion

  # Previous Site's Routes
  #get 'home/flight-training', to: 'pages#why_simplifly'
  #get 'program-pricing', to: 'pages#cost'
  #get 'programs', to: 'pages#pilot_training'
  get 'book-a-flight', to: 'discover_flights#new'
  #get 'locations', to: 'messages#location'
  get 'contact-us', to: 'messages#new'
  #get 'simplifying-your-training', to: 'pages#why_simplifly'
  #get 'flight-instructors', to: 'pages#our_team'
  #get 'category/pilot', to: 'pages#airline_pilot_courses'
  get 'becoming-a-pilot-timeline', to: 'pages#timeline'
  #get 'private-pilots-license', to: 'pages#private_pilot'
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  before_validation :strip_phone_number
  after_save :to_lacrm

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true, format: { with: /\A\d{10}\z/, message: "must be a valid 10-digit phone number" }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }

  def strip_phone_number
    self.phone = phone.to_s.gsub(/[-() ]/, "")
  end

  def to_lacrm
    api_key = ENV['LACRM_API']
    # Set the endpoint and headers
    endpoint = "https://api.lessannoyingcrm.com/v2/"
    headers = {
      "Authorization" => api_key,
      "Content-Type" => "application/json"
    }
    # Get the user ID
    user_payload = {
      "Function" => "GetUser",
      "Parameters" => {}
    }
    user_response = HTTParty.get(endpoint, headers: headers, body: user_payload.to_json)
    if user_response.code == 200
      user_id = JSON.parse(user_response.body)['UserId']
    else
      # Handle the error
      user_id = nil
    end

    # Create the contact
    contact_payload = {
      "Function" => "CreateContact",
      "Parameters" => {
        "IsCompany" => false,
        "AssignedTo" => user_id,  #need to just get the USER ID so I can avoid doin the get call each time..
        "Name" => "#{self.first_name} #{self.last_name}",
        "Email" => "#{self.email}",
        "Phone" => "#{self.phone}",
        "Background Info" => "Originated from enrollment form on website",
      }
    }


    

    response = HTTParty.post(endpoint, headers: headers, body: contact_payload.to_json)
    contact_id = JSON.parse(response.body)['ContactId']
    

    # Add a note
    note_payload = {
      "Function" => "CreateNote",
      "Parameters" => {
        "ContactId" => contact_id,
        "Note" => "
          Previous Training: #{self.previous_training}
          Goals: #{self.goals}
          Comments: #{self.comments}

          Selected Date: #{self.preferred_date}
          Selected Time: #{self.preferred_availability}
          Alternate Date: #{self.alternate_date}
          Alternate Time: #{self.alternate_availability}
        ",
      }
    }
    HTTParty.post(endpoint, headers: headers, body: note_payload.to_json)

  end  
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:create, :new, :confirmation]
  invisible_captcha only: [:create], honeypot: :confirm_email

  # GET /enrollments or /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  def confirmation
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        EnrollmentMailer.enrollment_email(@enrollment).deliver_later
        format.html { redirect_to enroll_confirmation_path, notice: @enrollment.first_name }
        #format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  ## PATCH/PUT /enrollments/1 or /enrollments/1.json
  #def update
  #  respond_to do |format|
  #    if @enrollment.update(enrollment_params)
  #      format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
  #      format.json { render :show, status: :ok, location: @enrollment }
  #    else
  #      format.html { render :edit, status: :unprocessable_entity }
  #      format.json { render json: @enrollment.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:first_name, :last_name, :phone, :email, :goals, :previous_training, :comments, :preferred_date, :preferred_availability, :alternate_date, :alternate_availability, :location)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.erb
<div id="<%= dom_id enrollment %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">First name:</strong>
    <%= enrollment.first_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Last name:</strong>
    <%= enrollment.last_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone:</strong>
    <%= enrollment.phone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= enrollment.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Goals:</strong>
    <%= enrollment.goals %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Location:</strong>
    <%= enrollment.location %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Previous training:</strong>
    <%= enrollment.previous_training %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Comments:</strong>
    <%= enrollment.comments %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Preferred date:</strong>
    <%= enrollment.preferred_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Preferred availability:</strong>
    <%= enrollment.preferred_availability %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Alternate date:</strong>
    <%= enrollment.alternate_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Alternate availability:</strong>
    <%= enrollment.alternate_availability %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this enrollment", enrollment, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this enrollment', edit_enrollment_path(enrollment), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/enrollments/confirmation.html.erb
<%= render "shared/header" %>
<main class="bg-slate-50 w-full flex flex-col items-center justify-center">
  <!--Container for contents-->
  <div class="lg:w-3/5 md:w-4/5 pb-10">
    <h1 class="font-bold text-4xl py-10 text-center">You can be a pilot!</h1>  
    <p class="px-5 p-text pb-5">
    Thank you<%if notice.present?%>, <%= notice %>,<%end%> for applying to enroll at SimpliFly!
    A member of our team will be in touch shortly to talk about your aviation goals. You can also give us a call at <%=link_to "1-480-256-8355", "tel:1-480-256-8355" %> or email us at <%= mail_to 'info@simpliflyco.com', class: "text-slate-800 hover:underline"%>
    </p>

  </div>
  
  <div class="flex flex-col lg:flex-row lg:items-center">
    <div class="lg:w-1/2 lg:px-10">
      <h2 class="font-bold text-2xl py-10 text-center">Consider Taking a Discovery Flight</h2>
      <p class="p-text px-5 pb-5">
        Your Discovery Flight is designed to give you a taste of what it's like to be a pilot. You'll spend approximately 30 minutes in the air with one of our certified flight instructors, who will guide you through the basics of flying and answer any questions you may have. You'll also have the opportunity to take the controls and experience the thrill of flying first-hand.
      </p>
      <p class="p-text px-5 pb-5">
        If you're interested in taking a discovery flight, please mention this when you talk to one of our team members.
      </p>
      <div class="pt-10 flex flex-row gap-3 justify-center">
        <%= link_to pilot_training_path do %>
          <div class="btn-primary mb-10">
            VIEW PROGRAMS
          </div>
        <% end %>

        <%= link_to root_path do %>
          <div class="btn-primary mb-10">
            HOME PAGE
          </div>
        <% end %>
      </div>
    </div>
    <div class="lg:w-1/2 lg:px-10 flex flex-col items-center">
      <%= image_tag "plane-flying.webp", class: "lg:w-3/4", alt: "Plane flying over Falcon Field"%>
    </div>
  </div>

</main>

<%= render "shared/footer"%>

app/views/enrollments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing enrollment</h1>

  <%= render "form", enrollment: @enrollment %>

  <%= link_to "Show this enrollment", @enrollment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to enrollments", enrollments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/enrollments/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Enrollments</h1>
    <%= link_to 'New enrollment', new_enrollment_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="enrollments" class="min-w-full">
    <%= render @enrollments %>
  </div>
</div>

app/views/enrollments/new.html.erb
<%# Head / Meta Data %>
<% title("Enroll to be a Pilot at BlueBird") %>
<% meta_description("Enroll at BlueBird, the leading flight school in Mesa, Phoenix, Scottsdale, and Spanish Fork, Salt Lake. Start your pilot training with us and embark on an exciting career in aviation.") %>
<% meta_keywords("Enroll at BlueBird, Flight School Enrollment, Marthasville Flight School, Phoenix Flight School, Scottsdale Flight School, Spanish Fork Flight School, Salt Lake Flight School") %>

<header class="w-full bg-behind h-screen lg:h-screen bg-cover bg-center flex flex-col justify-between items-center">
  <div class="px-5 py-40 lg:py-52 flex flex-col justify-center items-start w-full h-full">
      <h1 class="font-semibold text-5xl text-center lg:text-start font-header uppercase">Are you ready to become a pilot?</h1>
      <h2 class="font-bold text-4xl text-center lg:text-start py-10 ">Fill out an application to enroll at BlueBird</h2>
      <div class="w-full flex flex-col items-center lg:hidden">
        <a href="#quiz-frame", class="btn-primary"
        onclick="event.preventDefault(); document.getElementById('quiz-frame').scrollIntoView({ behavior: 'smooth' });">
          START NOW
        </a>
      </div>
  </div>

  

  <div class="hidden lg:block lg:fixed  right-5 top-10 z-50 bg-white rounded-xl border pb-5 overflow-y-auto max-h-[88vh]">
  <%= render "form", enrollment: @enrollment %>
  </div>
</header>

<section class="flex flex-col items-start bg-gradient-to-b from-sky-200 to slate-400">
  <div class="lg:w-2/3 flex flex-col items-center">
    <h2 class="font-header uppercase font-semibold text-4xl pt-20 pb-10 text-center">Why Fly at SimpliFly?</h2>
    <p class="max-w-2xl px-5 pb-10">
      Your success is our <strong>priority</strong>.  Learning to fly is a transformative experience, and we are dedicated to providing you with the knowledge, skills, and support you need to reach new heights. Whether your goal is to fly for pleasure or pursue a professional career as a pilot, we'll ensure you receive the highest quality training that sets you up for success.
    </p>
    <h2 class="font-header uppercase font-semibold text-4xl pb-10 text-center">Programs to Fit Your Schedule</h2>
    <p class="max-w-2xl px-5 pb-10">
      Pursuing your passion for flying shouldn't mean sacrificing your other commitments. That's why we offer a range of programs designed to fit seamlessly into your busy schedule. Whether you prefer an accelerated full time training program or a flexible part time option, we have the perfect solution to match your needs.
    </p>
    <h2 class="font-header uppercase font-semibold text-4xl pb-10 text-center">Start Your Career</h2>
    <p class="max-w-2xl px-5 pb-10">
      Many of our students have completed our pilot training programs and then moved to the airlines.  This is your chance to be a part of the action.  If you're looking to start a career in aviation or even if you want to pursue aviation as a hobby, fill out the form on this page and let's get in touch. 
    </p>

    <div class="pt-10 flex flex-row gap-3 justify-center">
      <%= link_to pilot_training_path do %>
        <div class="btn-secondary mb-10">
          VIEW PROGRAMS
        </div>
      <% end %>
      <a href="#top", class="hidden lg:block"
        onclick="event.preventDefault(); document.getElementById('top').scrollIntoView({ behavior: 'smooth' });">
        <div class="btn-primary mb-10 border-2 border-sky-500 hover:border-sky-600 lg:px-16">
        FLY NOW
        </div>
      </a>
      <a href="#quiz-frame", class="lg:hidden"
        onclick="event.preventDefault(); document.getElementById('quiz-frame').scrollIntoView({ behavior: 'smooth' });">
        <div class="btn-primary mb-10 border-2 border-sky-500 hover:border-sky-600 lg:px-16">
        FLY NOW
        </div>
      </a>
    </div>
  </div>

  


</section>

<!--desktop-->
  <div class="hidden lg:block w-full px-4 bg-white opacity-50">
    <%= render "shared/bottom_footer"%>
  </div>

<!--Mobile // use turbo frame to keep view in place-->
<turbo-frame id="quiz-frame">
  <div class="lg:hidden right-5 top-10 z-50 bg-white pb-5 overflow-y-auto">
    <%= render "form", enrollment: @enrollment %>
  </div>
</turbo-frame>




<div class="lg:hidden w-full bg-ideal-blue-darker pt-16 pb-5 pl-5">
  <%= render "shared/bottom_footer"%>
</div>

app/views/enrollments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @enrollment %>

    <%= link_to 'Edit this enrollment', edit_enrollment_path(@enrollment), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this enrollment', enrollment_path(@enrollment), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to enrollments', enrollments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>